
tasks:
- name: Couchbase
  init:  apt-get -qq update && \
    apt-get -qq install curl && \
    mkdir -p /tmp/couchbase && \
    cd /tmp/couchbase && \
    curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-amd64.deb && \
    dpkg --unpack ./couchbase-release-1.0-amd64.deb && \
    apt-get -qq update && \
    apt-get -qq install couchbase-server

# exposed ports
ports:
- port: 8091
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
