version: '3.4'

services:
  couchbase:
    image: btburnett3/couchbasefakeit:enterprise-6.0.1
    environment:
      CB_INDEXSTORAGE: memory_optimized
    volumes:
    - "./couchbase:/startup" # local ./couchbase folder where couchbasefakeit configuration files are located
    ports:
    - "8091:8091" # Allows local access to mgmt UI
    - "8092:8092"
    - "8093:8093"
    - "8094:8094"
    - "11210:11210"